# -*- coding: utf-8 -*-
"""Batalha Naval.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kjaA8wwxA1VZUFshwgC-BhVXw4ktvr28
"""

from random import randint

def imprimir_matriz(matriz,jogador):
  s = [[str(e) for e in row] for row in matriz]
  lens = [max(map(len, col)) for col in zip(*s)]
  fmt = '\t'.join('{{:{}}}'.format(x) for x in lens)
  table = [fmt.format(*row) for row in s]
  print(f"\nVISÃO DO TABULEIRO {jogador}\n------------------------------------------------------------ \n")
  print('\n'.join(table))

#Tabuleiro
matriz_jogador = []
matriz_computador = []

qtdLinhas = 10
qtdColunas = 10

#Verificação de 0 e 1
def tem_barco(matriz):
  for i in range(0,qtdLinhas):
    for j in range(0,qtdColunas):
      if matriz[i][j] == 1:
        return True
  return False

for i in range(0,qtdLinhas):
  matriz_jogador.append([0]*qtdColunas)

for i in range(0,qtdLinhas):
  matriz_computador.append([0]*qtdColunas)

#Posicionamento dos barcos
for i in range(4):
  preenchido = True
  while(preenchido):
    x = int(input("Digite uma coordena de linha: "))
    y = int(input("Digite uma coordena coluna: "))
    if (x>9 or y>9):
      posicao_valida=False
      while posicao_valida==False:
        print("posição inválida, tente novamente")
        x = int(input("Digite uma coordena de linha: "))
        y = int(input("Digite uma coordena coluna: "))
        if (x<=9 and y<=9):
          posicao_valida=True
    if (matriz_jogador[x][y] == 0):
      preenchido = False
      matriz_jogador[x][y] = 1  

for i in range(4):
  preenchido = True
  while(preenchido):
    x = randint(0,9)
    y = randint(0,9)
    if (matriz_computador[x][y] == 0):
      preenchido = False
      matriz_computador[x][y] = 1  

imprimir_matriz(matriz_jogador,"jogador")
#imprimir_matriz(matriz_computador,"computador")

#Jogada do jogador
terminou = False
while terminou == False:
  jogada1_jogador =  int(input(print("Escolha uma linha para atacar: ")))
  jogada2_jogador =  int(input(print("Escolha um coluna para atacar: ")))
  if (jogada1_jogador>9 or jogada2_jogador>9):
    jogada_valida=False
    while jogada_valida==False:
      print("jogada inválida, jogue novamente")
      jogada1_jogador =  int(input("Escolha uma linha para atacar: "))
      jogada2_jogador =  int(input("Escolha um coluna para atacar: "))
      if (jogada1_jogador<=9 and jogada2_jogador<=9):
        jogada_valida=True
  if matriz_computador [jogada1_jogador][jogada2_jogador]:
    matriz_computador [jogada1_jogador][jogada2_jogador] = 0
    print("Você acertou!")
  else: 
    print("Você errou!")

#Jogada do computador
  jogada1_computador = randint(0,9)
  jogada2_computador = randint(0,9)
  if matriz_jogador [jogada1_computador][jogada2_computador]:
    matriz_jogador [jogada1_computador][jogada2_computador] = 0
    print("Computador acertou!")
    imprimir_matriz(matriz_jogador,"jogador")
  else: 
    print("Computador errou!")

#Verificação se ganhou
  jogadorTemBarco = tem_barco(matriz_jogador)
  computadorTemBarco = tem_barco(matriz_computador)

  if (jogadorTemBarco == False):
    terminou = True
    print("Computador ganhou")

  if (computadorTemBarco == False):
    terminou = True
    print("Jogador ganhou")