# -*- coding: utf-8 -*-
"""lista de atividades 3 revisão  abrangente

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12HmoKdcWRBn2dgjpYUVNiT-lV13Muxf2
"""

num = int(input("digite um número!"))
algarismos = [int(a) for a in str(num)]
lista= []
for i in algarismos:
  potenciacao= i**len(algarismos)
  lista.append(int(potenciacao))
if sum(lista)==(num):
  print(num,"é um número narcisista")
else:
  print(num,"não é um número narcisista")

hora_inicio = int(input("Digite a hora de início"))
minuto_inicio = int(input("Digite o minuto de início"))
valor_minuto = 1

hora_fim = int(input("Digite a hora de fim"))
minuto_fim = int(input("Digite o minuto de fim"))

final = hora_fim * 60 + minuto_fim
inicio = hora_inicio * 60 + minuto_inicio

diferenca_em_minutos = final - inicio

print("A ligação durou", {diferenca_em_minutos}, "minutos")

desconto = 50
if (hora_inicio >= 0 and hora_inicio <= 9):
  if (hora_fim >= 0 and hora_fim <= 9): 
    dif = final - inicio
    print("Minutos com desconto: ", dif)
    print("Valor cobrado: ", dif * (valor_minuto * 0.5))
  else:
    if (hora_fim > 9 and hora_fim <= 18):
      normal = final - 9 * 60
      desc_um = 9 * 60 - inicio
      print("Minutos com desconto", desc_um)
      valor_desc = desc_um * (valor_minuto * 0.5)
      print("Valor com desconto", valor_desc)
      print("Valor sem desconto", normal)
      print("Total da ligação", normal + valor_desc)
    elif (hora_fim > 18 and hora_fim <= 21):
      normal = 9 * 60
      desc_um = 9 * 60 - inicio
      desc_dois= (final-18*60)
      print("Minutos com primeiro desconto", desc_um)
      print("Minutos sem desconto", normal)
      print("Minutos com segundo desconto", desc_dois)
      valor_desc = (desc_um * (valor_minuto * 0.5))+(desc_dois*(valor_minuto*0,3))
      print("Valor com desconto", valor_desc)
      print("Valor sem desconto", normal)
      print("Total da ligação", normal + valor_desc)
    else:
      normal = 9 * 60
      desc_um = 9 * 60 - inicio
      desc_dois= 3 * 60
      desc_tres= (final-21*60)
      print("Minutos com primeiro desconto", desc_um)
      print("Minutos sem desconto", normal)
      print("Minutos com segundo desconto", desc_dois)
      print("Minutos com terceiro desconto", desc_tres)
      valor_desc = (desc_um * (valor_minuto * 0.5))+(desc_dois*(valor_minuto*0,3))+(desc_tres*(valor_minuto*0,4))
      print("Valor com desconto", valor_desc)
      print("Valor sem desconto", normal)
      print("Total da ligação", normal + valor_desc)

elif (hora_inicio >9 and hora_inicio <= 18):
  if (hora_fim >= 9 and hora_fim <= 18): 
    dif = final - inicio
    print("Valor cobrado: ", dif )
  else:
    if (hora_fim >= 18 and hora_fim <= 21):
      normal = 18 * 60 -inicio
      desc_dois= final- 18 * 60
      print("Minutos com desconto", desc_dois)
      valor_desc = desc_dois * (valor_minuto * 0.3)
      print("Valor com desconto", valor_desc)
      print("Valor sem desconto", normal)
      print("Total da ligação", normal + valor_desc)
    else:
      normal = 18 * 60 -inicio
      desc_dois= 3 * 60
      desc_tres= final - 21*60
      print("Minutos com segundo desconto", desc_dois)
      print("Minutos sem desconto", normal)
      print("Minutos com terceiro desconto", desc_tres)
      valor_desc = (desc_dois * (valor_minuto * 0.3))+(desc_tres*(valor_minuto*0,4))
      print("Valor com desconto", valor_desc)
      print("Valor sem desconto", normal)
      print("Total da ligação", normal + valor_desc)

elif (hora_inicio > 18 and hora_inicio <= 21):
  if(hora_fim >= 18 and hora_fim <= 21): 
    dif = final - inicio
    print("Minutos com desconto: ", dif)
    print("Valor cobrado: ", dif * (valor_minuto * 0.3))
  else:
    desc_dois=21*60-inicio
    desc_tres= final-21*60
    print("Minutos com segundo desconto", desc_dois)
    print("Minutos com terceiro desconto", desc_tres)
    valor_desc = (desc_dois * (valor_minuto * 0.3))+(desc_tres*(valor_minuto*0,4))
    print("Total da ligação", valor_desc)
else:
  dif = (23*60+59) - inicio
  print("Minutos com desconto: ", dif)
  print("Valor cobrado: ", dif * (valor_minuto * 0.4))