# -*- coding: utf-8 -*-
"""lista 10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RRGILtn9_X4eaZE_CNQH5or_lw6rHbMl
"""

#questão 1

from random import randint
x=randint(0,6)
y=randint(0,6)
z=randint(0,6)
k=randint(0,6)
matriz= [[x,y],[z,k]]
resultante= [[0,0],[0,0]]
print("a primeira matriz é ", matriz)
maior=-1
for i in range(2):
  for j in range(2):
    if (matriz[i][j] > maior):
      maior = matriz[i][j]
for i in range(2):
  for j in range(2):
    resultante[i][j] = matriz[i][j] * maior
print("a matriz resultante é ",resultante)

#questão 2
import numpy as np
import random

notas = np.zeros((10,3))
menorNota= [0,0,0]

for aluno in range(10):
  for notaAluno in range(3):
    print("Digite a nota ", notaAluno, "para o aluno ", aluno, ": ")
    notas[aluno][notaAluno]= float ( input() )

print(notas)

for aluno in range(10):
  numeroProva = 0
  menor = 11
  for notaAluno in range(3):
    if (notas[aluno][notaAluno] < menor):      
      menor = notas[aluno][notaAluno]
      numeroProva = notaAluno
  print("Aluno ", aluno, " Menor nota ", menor, "na prova", numeroProva)
  menorNota[numeroProva] += 1

for i in range(3):
  print("Número de notas mais baixas por prova ", i, ": ", menorNota[i])

#questão 3
from random import randint
matriz=[[0]*20]*10
soma=[0]*10

for i in range(0,10):
  for j in range(0,20):
    matriz[i][j] = randint(0,9)
    soma[i] = soma[i] + matriz[i][j]

for i in range(0,10):
  for j in range(0,20):
    matriz[i][j] = soma[i]* matriz[i][j]

for i in range(0,10):
  for j in range(0,20):
    print(matriz[i][j])