# -*- coding: utf-8 -*-
"""lista avaliativa de atividades (1)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E4TcCDAbNUlrQl9Iro2m36wSf6hmp_kS
"""

nome= input (   "Digite aqui o seu nome:"   )   
print (   "olá"   , nome)   
ano=    int   ( input (   "digite aqui seu ano de nascimento: "   ))   
idade= (   2022   - ano)   
print (nome,    " tem"   , idade,    "anos"    )

fabrica= float(input("valor de fábrica "))
distribuidor= fabrica * 0.28
imposto= fabrica * 0.45

carro= fabrica + distribuidor + imposto
print("o valor final será", carro)

nota_um=float( input("digite aqui sua primeira nota: "))
nota_dois=float (input(" digite aqui sua segunda nota: "))
nota_tres=float (input(" digite aqui sua terceira nota: "))
pesoum= nota_um * 2       
pesodois= nota_dois *4
pesotres= nota_tres *6
media= (pesoum + pesodois + pesotres)/12       
print ("sua nota foi", media)