# -*- coding: utf-8 -*-
"""moedas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ikVN_4LDxinizEHACRZq9ko4vj_X7Gr0
"""

total = int(input("digite a quantidade de centavos \n"))
real = int(total) // 100
cinquenta = int((total % 100) // 50)
vinte_e_cinco = int(((total % 100) % 50) // 25)
dez = int((((total % 100) % 50) % 25) // 10)
cinco = int(((((total % 100) % 50) % 25) % 10) // 5)
print("você receberá: \n", real, "moedas de um real \n" , cinquenta, "moedas de 50 centavos \n", vinte_e_cinco, "moedas de 25 centavos \n" , dez, "moedas de 10 centavos \n", cinco, "moedas de cinco centavos.")