# -*- coding: utf-8 -*-
"""olá mundo e bhaskara

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1thjxCsZ6q2S0QHE4RkPqycWe7sBvqrov
"""

print("olá mundo")

a= 1
b=8
c=7
delta = ((b)**2)-4*(a)*(c)
delta = (delta)**(0.5)
xa= (-(b)+(delta))/2*(a)
xb= (-(b)-(delta))/2*(a)
print("o valor de x pode ser",xa,"ou",xb)