# -*- coding: utf-8 -*-
"""vetor

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DvOVuXoiY09pLx7WjrRXyXV5XC9hcFPA
"""

presentes=[]

presentes.append("João")

presentes.append("Matheus")

presentes.insert(1,"julio")

presentes[2]="murilo"

print(presentes)

presentes.pop(1)
a = presentes
print(a)

comecarne=["joao","pedro","murilo","matheus"]

vegano=["Julio","Juliana","Bondicz","matheus"]

total=comecarne+vegano

len(total)